import '../../../inspections/domain/entities/inspection_entity.dart';
import '../../../maintenance/infra/models/maintenance_record.dart';
import '../../domain/entities/template_entities.dart';

/// Converts existing generator records into revision-pinned Phase 3 responses.
///
/// Canonical values are populated only where the old field has a direct
/// semantic equivalent. The complete JSON-safe legacy payload remains embedded
/// under `_legacyPayload` so migration/parity tooling can recover evidence that
/// is not represented by the first template revision.
class LegacyGeneratorResponseAdapter {
  const LegacyGeneratorResponseAdapter._();

  static FormResponse inspection({
    required InspectionEntity source,
    required FormTemplateDefinition definition,
    required String responseId,
    TemplateResponseStatus status = TemplateResponseStatus.completed,
  }) {
    _requirePack(definition, 'generator-inspection');
    final canonical = <String, dynamic>{
      'siteCode': source.siteCode,
      'siteGrade': source.siteGrade,
      'address': source.address,
      'serviceDate': _date(source.serviceDate),
      'technicianName': source.technicianName,
      'generatorMake': source.generatorMake,
      'generatorModel': source.generatorModel,
      'generatorSerial': source.generatorSerial,
      'generatorKw': source.generatorKw,
      'engineHours': source.engineHours,
      'fuelType': source.fuelType,
      'voltageRating': source.voltageRating,
      'locIndoors': source.locIndoors,
      'locOutdoors': source.locOutdoors,
      'locRoof': source.locRoof,
      'locBasement': source.locBasement,
      'locOther': source.locOther,
      'dedicatedRoom2hr': source.dedicatedRoom2hr,
      'separateFromMainService': source.separateFromMainService,
      'areaClear': source.areaClear,
      'labelsAndEStopVisible': source.labelsAndEStopVisible,
      'extinguisherPresent': source.extinguisherPresent,
      'fuelStoredType': source.fuelStoredType,
      'fuelQtyGallons': source.fuelQtyGallons,
      'fdnyPermit': source.fdnyPermit,
      'c92OnSite': source.c92OnSite,
      'gasCutoffValve': source.gasCutoffValve,
      'depSizeKw': source.depSizeKw,
      'depRegisteredCats': source.depRegisteredCats,
      'depCertificateOperate': source.depCertificateOperate,
      'tier4Compliant': source.tier4Compliant,
      'smokeOrStackTest': source.smokeOrStackTest,
      'recordsKept5Years': source.recordsKept5Years,
      'emergencyOnly': source.emergencyOnly,
      'estimatedAnnualRuntimeHours': source.estimatedAnnualRuntimeHours,
      'fuelFor6hrs': source.fuelFor6hrs,
      'notes': source.notes,
      'gensetRunsUnderLoad': source.gensetRunsUnderLoad,
      'voltageFrequencyOk': source.voltageFrequencyOk,
      'exhaustOk': source.exhaustOk,
      'groundingBondingOk': source.groundingBondingOk,
      'controlPanelOk': source.controlPanelOk,
      'safetyDevicesOk': source.safetyDevicesOk,
      'deficienciesDocumented': source.deficienciesDocumented,
      'loadbankDone': source.loadbankDone,
      'atsVerified': source.atsVerified,
      'fuelStoredOver1Yr': source.fuelStoredOver1Yr,
      'lastServiceDate': source.lastServiceDate,
      'oilFilterChangeDate': source.oilFilterChangeDate,
      'fuelFilterDate': source.fuelFilterDate,
      'coolantFlushDate': source.coolantFlushDate,
      'batteryReplaceDate': source.batteryReplaceDate,
      'airFilterDate': source.airFilterDate,
      'technicianSignaturePath': source.technicianSignaturePath,
      'technicianSigDate': _date(source.technicianSigDate),
      'customerName': source.customerName,
      'customerSignaturePath': source.customerSignaturePath,
      'customerSigDate': _date(source.customerSigDate),
    };
    _removeEmptyStrings(canonical);
    canonical['_legacy'] = {
      'source': 'InspectionEntity',
      'sourceId': source.id,
      'adapted': true,
      'validationEnforcedAtMigration': false,
      'booleanSemantics': 'Stored false may be an explicit answer or a legacy default.',
      'externalCollections': ['load_tests', 'photo_attachments'],
    };
    canonical['_legacyPayload'] = _inspectionPayload(source);

    return FormResponse(
      id: responseId,
      tenantId: definition.template.tenantId,
      templateId: definition.template.id,
      templateRevisionId: definition.revision.id,
      status: status,
      subjectType: 'generator_inspection',
      subjectId: source.id,
      inspectionId: source.id,
      values: canonical,
      completedAt: status == TemplateResponseStatus.completed ? source.updatedAt : null,
      completedByUserId: null,
      createdAt: source.createdAt,
      updatedAt: source.updatedAt,
    );
  }

  static FormResponse maintenance({
    required MaintenanceRecord source,
    required FormTemplateDefinition definition,
    required String tenantId,
    required String responseId,
  }) {
    _requirePack(definition, 'generator-maintenance');
    if (definition.template.tenantId != tenantId) {
      throw ArgumentError('Maintenance response tenant must match the template tenant.');
    }
    final canonical = _maintenancePayload(source);
    _removeEmptyStrings(canonical);
    canonical['_legacy'] = {
      'source': 'MaintenanceRecord',
      'sourceId': source.id,
      'adapted': true,
      'validationEnforcedAtMigration': false,
      'booleanSemantics': 'Stored false may be an explicit answer or a legacy default.',
    };
    canonical['_legacyPayload'] = _maintenancePayload(source);
    final status = source.completed
        ? TemplateResponseStatus.completed
        : TemplateResponseStatus.draft;

    return FormResponse(
      id: responseId,
      tenantId: tenantId,
      templateId: definition.template.id,
      templateRevisionId: definition.revision.id,
      status: status,
      subjectType: 'generator_maintenance',
      subjectId: source.id,
      inspectionId: source.inspectionId,
      maintenanceRecordId: source.id,
      values: canonical,
      completedAt: source.completed ? source.updatedAt : null,
      completedByUserId: null,
      createdAt: source.createdAt,
      updatedAt: source.updatedAt,
    );
  }

  static void _requirePack(FormTemplateDefinition definition, String slug) {
    if (definition.template.slug != slug ||
        definition.revision.status != TemplateRevisionStatus.published) {
      throw ArgumentError('Legacy records require the published $slug definition.');
    }
  }

  static Map<String, dynamic> _inspectionPayload(InspectionEntity source) => {
        'id': source.id,
        'createdAt': source.createdAt.toUtc().toIso8601String(),
        'updatedAt': source.updatedAt.toUtc().toIso8601String(),
        'siteCode': source.siteCode,
        'siteGrade': source.siteGrade,
        'address': source.address,
        'serviceDate': source.serviceDate.toUtc().toIso8601String(),
        'technicianName': source.technicianName,
        'generatorMake': source.generatorMake,
        'generatorModel': source.generatorModel,
        'generatorSerial': source.generatorSerial,
        'generatorKw': source.generatorKw,
        'engineHours': source.engineHours,
        'fuelType': source.fuelType,
        'voltageRating': source.voltageRating,
        'locIndoors': source.locIndoors,
        'locOutdoors': source.locOutdoors,
        'locRoof': source.locRoof,
        'locBasement': source.locBasement,
        'locOther': source.locOther,
        'dedicatedRoom2hr': source.dedicatedRoom2hr,
        'separateFromMainService': source.separateFromMainService,
        'areaClear': source.areaClear,
        'labelsAndEStopVisible': source.labelsAndEStopVisible,
        'extinguisherPresent': source.extinguisherPresent,
        'fuelStoredType': source.fuelStoredType,
        'fuelQtyGallons': source.fuelQtyGallons,
        'fdnyPermit': source.fdnyPermit,
        'c92OnSite': source.c92OnSite,
        'gasCutoffValve': source.gasCutoffValve,
        'depSizeKw': source.depSizeKw,
        'depRegisteredCats': source.depRegisteredCats,
        'depCertificateOperate': source.depCertificateOperate,
        'tier4Compliant': source.tier4Compliant,
        'smokeOrStackTest': source.smokeOrStackTest,
        'recordsKept5Years': source.recordsKept5Years,
        'emergencyOnly': source.emergencyOnly,
        'estimatedAnnualRuntimeHours': source.estimatedAnnualRuntimeHours,
        'fuelFor6hrs': source.fuelFor6hrs,
        'notes': source.notes,
        'gensetRunsUnderLoad': source.gensetRunsUnderLoad,
        'voltageFrequencyOk': source.voltageFrequencyOk,
        'exhaustOk': source.exhaustOk,
        'groundingBondingOk': source.groundingBondingOk,
        'controlPanelOk': source.controlPanelOk,
        'safetyDevicesOk': source.safetyDevicesOk,
        'deficienciesDocumented': source.deficienciesDocumented,
        'loadbankDone': source.loadbankDone,
        'atsVerified': source.atsVerified,
        'fuelStoredOver1Yr': source.fuelStoredOver1Yr,
        'lastServiceDate': source.lastServiceDate,
        'oilFilterChangeDate': source.oilFilterChangeDate,
        'fuelFilterDate': source.fuelFilterDate,
        'coolantFlushDate': source.coolantFlushDate,
        'batteryReplaceDate': source.batteryReplaceDate,
        'airFilterDate': source.airFilterDate,
        'technicianSignaturePath': source.technicianSignaturePath,
        'technicianSigDate': source.technicianSigDate.toUtc().toIso8601String(),
        'customerSignaturePath': source.customerSignaturePath,
        'customerSigDate': source.customerSigDate.toUtc().toIso8601String(),
        'customerName': source.customerName,
        'pdfPath': source.pdfPath,
        'scheduledAt': source.scheduledAt.toUtc().toIso8601String(),
        'nextDueAt': source.nextDueAt?.toUtc().toIso8601String(),
        'tenantId': source.tenantId,
        'assignedToUserId': source.assignedToUserId,
      };

  static Map<String, dynamic> _maintenancePayload(MaintenanceRecord source) => {
        'id': source.id,
        'inspectionId': source.inspectionId,
        'siteCode': source.siteCode,
        'address': source.address,
        'dateOfService': source.dateOfService?.toUtc().toIso8601String(),
        'technicianName': source.technicianName,
        'generatorMake': source.generatorMake,
        'generatorModel': source.generatorModel,
        'generatorSerial': source.generatorSerial,
        'generatorKw': source.generatorKw,
        'engineHours': source.engineHours,
        'fuelType': source.fuelType,
        'lastFuelDeliveryDate': source.lastFuelDeliveryDate,
        'voltageRating': source.voltageRating,
        'generatorLocation': source.generatorLocation,
        'generatorLocationOther': source.generatorLocationOther,
        'enclosureDamaged': source.enclosureDamaged,
        'enclosureIntact': source.enclosureIntact,
        'noEnclosure': source.noEnclosure,
        'visibleDamageOrLeaks': source.visibleDamageOrLeaks,
        'areaClearOfHazards': source.areaClearOfHazards,
        'warningLabelsVisible': source.warningLabelsVisible,
        'fireExtinguisherPresent': source.fireExtinguisherPresent,
        'batteryNeedsReplace': source.batteryNeedsReplace,
        'batteryRecentlyReplaced': source.batteryRecentlyReplaced,
        'batteryMfgDate': source.batteryMfgDate,
        'batteryPartNo': source.batteryPartNo,
        'batteryType': source.batteryType,
        'airFilterNeedsReplace': source.airFilterNeedsReplace,
        'airFilterRecentlyReplaced': source.airFilterRecentlyReplaced,
        'airFilterLastReplacedDate': source.airFilterLastReplacedDate,
        'airFilterPartNo': source.airFilterPartNo,
        'coolantLevel': source.coolantLevel,
        'coolantColor': source.coolantColor,
        'coolantHosesCompromised': source.coolantHosesCompromised,
        'coolantHosesRecommendChange': source.coolantHosesRecommendChange,
        'coolantHosesInfo': source.coolantHosesInfo,
        'fuelHosesCompromised': source.fuelHosesCompromised,
        'fuelHosesRecommendChange': source.fuelHosesRecommendChange,
        'fuelHosesInfo': source.fuelHosesInfo,
        'airIntakeHosesCompromised': source.airIntakeHosesCompromised,
        'airIntakeHosesRecommendChange': source.airIntakeHosesRecommendChange,
        'airIntakeHosesInfo': source.airIntakeHosesInfo,
        'oilHosesCompromised': source.oilHosesCompromised,
        'oilHosesRecommendChange': source.oilHosesRecommendChange,
        'oilHosesInfo': source.oilHosesInfo,
        'additionalHosesCompromised': source.additionalHosesCompromised,
        'additionalHosesRecommendChange': source.additionalHosesRecommendChange,
        'additionalHosesInfo': source.additionalHosesInfo,
        'canLube': source.canLube,
        'canLubePartNo': source.canLubePartNo,
        'canFuel': source.canFuel,
        'canFuelPartNo': source.canFuelPartNo,
        'canWaterSep': source.canWaterSep,
        'canWaterSepPartNo': source.canWaterSepPartNo,
        'canOil': source.canOil,
        'canOilPartNo': source.canOilPartNo,
        'canOther1': source.canOther1,
        'canOther1Label': source.canOther1Label,
        'canOther1PartNo': source.canOther1PartNo,
        'canOther2': source.canOther2,
        'canOther2Label': source.canOther2Label,
        'canOther2PartNo': source.canOther2PartNo,
        'oilFilterChanged': source.oilFilterChanged,
        'oilFilterNotes': source.oilFilterNotes,
        'fuelFilterReplaced': source.fuelFilterReplaced,
        'fuelFilterNotes': source.fuelFilterNotes,
        'coolantFlushed': source.coolantFlushed,
        'coolantNotes': source.coolantNotes,
        'batteryReplaced': source.batteryReplaced,
        'batteryNotes': source.batteryNotes,
        'airFilterReplaced': source.airFilterReplaced,
        'airFilterNotes': source.airFilterNotes,
        'beltsHosesReplaced': source.beltsHosesReplaced,
        'beltsHosesNotes': source.beltsHosesNotes,
        'blockHeaterTested': source.blockHeaterTested,
        'blockHeaterNotes': source.blockHeaterNotes,
        'racorServiced': source.racorServiced,
        'racorNotes': source.racorNotes,
        'atsControllerInspected': source.atsControllerInspected,
        'atsControllerNotes': source.atsControllerNotes,
        'cdvrProgrammed': source.cdvrProgrammed,
        'cdvrNotes': source.cdvrNotes,
        'undervoltageRepaired': source.undervoltageRepaired,
        'undervoltageNotes': source.undervoltageNotes,
        'hazmatRemoved': source.hazmatRemoved,
        'hazmatNotes': source.hazmatNotes,
        'serviceObservations': source.serviceObservations,
        'postVerifyRunsUnderLoad': source.postVerifyRunsUnderLoad,
        'postCheckVoltFreq': source.postCheckVoltFreq,
        'postInspectExhaust': source.postInspectExhaust,
        'postVerifyGrounding': source.postVerifyGrounding,
        'postCheckControlPanel': source.postCheckControlPanel,
        'postEnsureSafetyDevices': source.postEnsureSafetyDevices,
        'postDocumentDeficiencies': source.postDocumentDeficiencies,
        'postLoadbankTest': source.postLoadbankTest,
        'postAtsFunctionality': source.postAtsFunctionality,
        'fuelStoredLong': source.fuelStoredLong,
        'partsOilTypeQty': source.partsOilTypeQty,
        'partsCoolantTypeQty': source.partsCoolantTypeQty,
        'partsFilterTypes': source.partsFilterTypes,
        'partsBatteryTypeDate': source.partsBatteryTypeDate,
        'partsBeltsHosesReplaced': source.partsBeltsHosesReplaced,
        'partsBlockHeaterWattage': source.partsBlockHeaterWattage,
        'partsCdvrSerial': source.partsCdvrSerial,
        'technicianSignatureName': source.technicianSignatureName,
        'technicianSignatureDate': source.technicianSignatureDate?.toUtc().toIso8601String(),
        'technicianSignaturePath': source.technicianSignaturePath,
        'customerSignatureName': source.customerSignatureName,
        'customerSignatureDate': source.customerSignatureDate?.toUtc().toIso8601String(),
        'customerSignaturePath': source.customerSignaturePath,
        'createdAt': source.createdAt.toUtc().toIso8601String(),
        'updatedAt': source.updatedAt.toUtc().toIso8601String(),
        'generalNotes': source.generalNotes,
        'completed': source.completed,
        'requiresFollowUp': source.requiresFollowUp,
        'followUpNotes': source.followUpNotes,
      };

  static String _date(DateTime value) =>
      value.toLocal().toIso8601String().split('T').first;

  static void _removeEmptyStrings(Map<String, dynamic> values) {
    values.removeWhere((_, value) => value is String && value.trim().isEmpty);
  }
}
